ktor:
  application:
    modules:
      - com.financemetrics.ApplicationKt.module
  deployment:
    port: 8080
    watch:
      - classes
      - resources

database:
  url: "jdbc:postgresql://localhost:5432/financemetrics"
  user: "postgres"
  password: "postgres"
